return {
    {'tpope/vim-surround'},
    {'Pocco81/true-zen.nvim'},
    {'Lukesmithxyz/vimling',
      ft = { "latex", "tex", ".tex" },
    },
    {'ferdinandyb/bibtexcite.vim',
      ft = { "latex", "tex", ".tex" },
    },
    {'lervag/vimtex',
      ft = { "latex", "tex", ".tex" },
    },
    {'xuhdev/vim-latex-live-preview',
      ft = { "latex", "tex", ".tex" },
    },
}
